### ISSUE TITLE
g++ error "undefined reference to"

### ISSUE THREAD

**Issue by sucv** [duanxianpi/QtLive2d#1]
![Capture](https://user-images.githubusercontent.com/29542672/223473299-191cf6ab-66dd-48e9-8b9f-11ca222e378d.PNG)

Hi, I am very new to c++. I am using Win10 with MinGW compiler to compile your project. It seems that my compiler cannot find `Framework.lib`? Please help!

Also, I don't quite understand your `step 5`, how to *compile Framework*? I see a `Framework.lib` already included in this repository.

Thanks!!

**Comment by duanxianpi** [comment]
Hi sucv, if you want to build the Sample on Win32, please use MSVC, MinGW is not supported. MSVC can be installed at [here](https://visualstudio.microsoft.com/vs/older-downloads/#visual-studio-2019-and-other-products). In addition, I update the code and add a instruction about how to build the Sample. You can pull the latest code, it is easier to build. Let me know if you have other questions.

**Comment by sucv** [comment]
Hi duanxianpi, thanks for your prompt update! It helped me a lot.

I can finally successfully build the sample and see Miku! Since eventually, I gotta use it on a Linux system, I choose to build it in Ubuntu 20 (hosted by Virtualbox). I started to build Qt6 from source code and was consumed by the deep rabbit hole. Then I manage to get the installer up and running...

I proposed a pull request to add a missing line in `Sample.pro`, so that the Linux compiler can find QOpenGLWidge.h.

**Comment by duanxianpi** [comment]
Cool, enjoy using QtLive2d! I update the code to be compatible with both Qt5 and Qt6. For Qt6 if we wanted use QOpenGLWidget we need add openglwidgets module instead of widgets. And in Qt5 we need add widgets module. So I fix it in the Sample.pro It should work fine right now. Thanks for you pull requests!
